import json,numpy as np,pandas as pd
from pathlib import Path
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score,classification_report,confusion_matrix
import run_avr_group_selection as avr
import run_multimodal_val_locked_suite as suite
import train_audio_broad_oof_meta_select_final_test as broad
import train_audio_group_consistency_pair_blend_select_final_test as ga
import train_audio_lift_source_blend_select_final_test as lift
import train_audio_specimen_contact_consensus_select_final_test as sp
import train_val_select_final_test as audio_base
ROOT=Path('/home/ttung05/Desktop/tree_base/tree_structures'); OUT=Path('outputs/audio_feature_benchmarks/specimen_clip_eff_blend_group_selection'); CLIP=Path('outputs/image_timm_features/vit_base_patch16_clip_224.openai_ft_in1k'); EFF=Path('outputs/image_timm_features/efficientnet_b3.ra2_in1k')
def seg(s): return s.astype(str).str.replace(r'_window_\d+.*$','',regex=True)
def specimen(s): return seg(s).str.replace(r'_segment_.*$','',regex=True)
def main():
 lock=json.load(open(OUT/'selection_lock.json')); b=lock['selected_candidate']; cw=float(b['clip_weight']); ew=float(b['efficientnet_weight']); iw=float(b['image_material_weight']); th=float(b['contact_threshold']); audio_base.configure_feature_set('total240')
 h=audio_base.load_manifest(ROOT/'audio_visual_dataset_default/dataset.csv','hand_train'); hf=suite.load_manifest(ROOT/'audio_visual_dataset_default/dataset.csv',ROOT/'audio_visual_dataset_default','hand_train'); yh=hf.y.to_numpy(np.int64); hs=specimen(hf.audio_file).to_numpy(); u,hi=np.unique(hs,return_inverse=True); xc=np.load(CLIP/'hand_train_full/X.npy').astype(np.float32); xe=np.load(EFF/'hand_train_full/X.npy').astype(np.float32); xc=np.vstack([xc[hi==i].mean(0) for i in range(len(u))]); xe=np.vstack([xe[hi==i].mean(0) for i in range(len(u))]); ys=np.array([yh[hi==i][0] for i in range(len(u))]); from sklearn.model_selection import StratifiedGroupKFold; folds=list(StratifiedGroupKFold(5,shuffle=True,random_state=42).split(np.arange(len(yh)),yh,hs)); ass=np.full(len(yh),-1,np.int64)
 for k,(_,va) in enumerate(folds): ass[va]=k
 high=ga.load_highsr_oof(Path('outputs')); pair=sp.load_pairwise_oof(Path('outputs/audio_feature_benchmarks/audio_log_consensus_pair_blend_select/oof_sources/pairwise_selected_clean_oof_proba.npy')); anchor=lift.anchor_lift_proba(h,high,pair); src=broad.load_train_sources(Path('outputs'),yh,ass,42); ap=lift.postprocess(h,lift.normalize(.95*anchor+.05*src['report_gate_onehot']),'segment_lift'); pc,lg=avr.avr_inputs(ap); sk=seg(hf.audio_file).to_numpy(); su,sc=np.unique(sk,return_inverse=True); smap={k:i for i,k in enumerate(u)}; ssi=np.array([smap[k] for k in specimen(pd.Series(su))]); segpc=np.array([pc[sc==i].mean() for i in range(len(su))]); segmat=np.vstack([suite.normalize(np.exp(lg[sc==i].mean(0,keepdims=True)))[0] for i in range(len(su))]); audio_spec=np.vstack([suite.normalize(segmat[ssi==i].mean(0,keepdims=True))[0] for i in range(len(u))]); mc=make_pipeline(StandardScaler(),LogisticRegression(C=3,max_iter=1200,class_weight='balanced',random_state=42)); me=make_pipeline(StandardScaler(),LogisticRegression(C=3,max_iter=1200,class_weight='balanced',random_state=42)); mc.fit(xc[ys>0],ys[ys>0]-1); me.fit(xe[ys>0],ys[ys>0]-1)
 test=audio_base.load_manifest(ROOT/'audio_visual_dataset_robo_default/dataset.csv','robot_test'); tf=suite.load_manifest(ROOT/'audio_visual_dataset_robo_default/dataset.csv',ROOT/'audio_visual_dataset_robo_default','robot_test'); y=tf.y.to_numpy(np.int64); xtc=np.load(CLIP/'robot_test/X.npy').astype(np.float32); xte=np.load(EFF/'robot_test/X.npy').astype(np.float32); ts=specimen(tf.audio_file).to_numpy(); tu,ti=np.unique(ts,return_inverse=True); txc=np.vstack([xtc[ti==i].mean(0) for i in range(len(tu))]); txe=np.vstack([xte[ti==i].mean(0) for i in range(len(tu))]); raw=pd.read_csv(ROOT/'audio_visual_dataset_robo_default/dataset.csv'); af=pd.read_csv('outputs/audio_feature_benchmarks/audio_lift_source_blend_select/reports/audio_lift_source_blend_select_final_test_predictions.csv'); assert np.array_equal(af.audio_file.astype(str),raw.audio_file.astype(str)); p=suite.normalize(af[suite.PROBA_COLUMNS].to_numpy(np.float64)); pc,lg=avr.avr_inputs(p); tk=seg(test.audio_file).to_numpy(); su2,sc2=np.unique(tk,return_inverse=True); tpc=np.array([pc[sc2==i].mean() for i in range(len(su2))]); tmat=np.vstack([suite.normalize(np.exp(lg[sc2==i].mean(0,keepdims=True)))[0] for i in range(len(su2))]); tsi=np.array([np.where(tu==specimen(pd.Series([k])).iloc[0])[0][0] for k in su2]); taudio=np.vstack([suite.normalize(tmat[tsi==i].mean(0,keepdims=True))[0] for i in range(len(tu))]); im=suite.normalize(cw*mc.predict_proba(txc)+ew*me.predict_proba(txe)); mat=suite.normalize((1-iw)*taudio+iw*im); predseg=np.where(tpc>=th,mat[tsi].argmax(1)+1,0); pred=predseg[sc2]; by=(y>0).astype(int); bp=(pred>0).astype(int); result={'split':'robot_test_final','protocol':lock['protocol'],'locked_candidate':b,'n':len(y),'accuracy_4class':accuracy_score(y,pred),'macro_precision_4class':precision_score(y,pred,average='macro',zero_division=0),'macro_recall_4class':recall_score(y,pred,average='macro',zero_division=0),'macro_f1_4class':f1_score(y,pred,average='macro',zero_division=0),'weighted_f1_4class':f1_score(y,pred,average='weighted',zero_division=0),'binary_macro_f1':f1_score(by,bp,average='macro',zero_division=0),'per_class_4class':classification_report(y,pred,labels=[0,1,2,3],target_names=['ambient','leaf','trunk','twig'],output_dict=True,zero_division=0),'confusion_matrix_4class':confusion_matrix(y,pred,labels=[0,1,2,3]).tolist(),'no_test_leakage':True}; (OUT/'clip_eff_blend_final_test_metrics.json').write_text(json.dumps(result,indent=2,default=float)); print(json.dumps(result,indent=2,default=float))
if __name__=='__main__': main()
