from __future__ import annotations
import json
from pathlib import Path
import numpy as np,pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,f1_score,precision_score,recall_score
import run_avr_group_selection as avr
import run_multimodal_val_locked_suite as suite
import train_audio_lift_source_blend_select_final_test as lift
import train_val_select_final_test as audio_base
ROOT=Path('/home/ttung05/Desktop/tree_base/tree_structures'); OUT=Path('outputs/audio_feature_benchmarks/segment_joint_material_group_selection'); IMG=Path('outputs/image_timm_features/vit_base_patch16_clip_224.openai_ft_in1k')
def seg(s): return s.astype(str).str.replace(r'_window_\d+.*$','',regex=True)
def main():
 lock=json.loads((OUT/'selection_lock.json').read_text()); assert not lock.get('test_loaded'); C=float(lock['selected_candidate']['C']); th=float(lock['selected_candidate']['contact_threshold']); audio_base.configure_feature_set('total240')
 hand=audio_base.load_manifest(ROOT/'audio_visual_dataset_default/dataset.csv','hand_train'); hf=suite.load_manifest(ROOT/'audio_visual_dataset_default/dataset.csv',ROOT/'audio_visual_dataset_default','hand_train'); yh=hf.y.to_numpy(np.int64); xh=np.load(IMG/'hand_train_full/X.npy').astype(np.float32); hk=seg(hf.audio_file).to_numpy(); hu,hc=np.unique(hk,return_inverse=True); hxs=np.vstack([xh[hc==i].mean(0) for i in range(len(hu))]); hys=np.array([yh[hc==i][0] for i in range(len(hu))]);
 # Fit joint material model on all hand contact segments using locked audio OOF logits.
 # Reconstruct OOF audio exactly from the persisted, already group-aware audio source.
 import train_audio_broad_oof_meta_select_final_test as broad,train_audio_group_consistency_pair_blend_select_final_test as ga,train_audio_specimen_contact_consensus_select_final_test as sp
 from sklearn.model_selection import StratifiedGroupKFold
 groups=hf.audio_file.astype(str).str.replace(r'_segment_.*$','',regex=True).to_numpy(); folds=list(StratifiedGroupKFold(5,shuffle=True,random_state=42).split(np.arange(len(yh)),yh,groups)); ass=np.full(len(yh),-1,np.int64)
 for k,(_,va) in enumerate(folds): ass[va]=k
 high=ga.load_highsr_oof(Path('outputs')); pair=sp.load_pairwise_oof(Path('outputs/audio_feature_benchmarks/audio_log_consensus_pair_blend_select/oof_sources/pairwise_selected_clean_oof_proba.npy')); anchor=lift.anchor_lift_proba(hand,high,pair); src=broad.load_train_sources(Path('outputs'),yh,ass,42); ap=lift.postprocess(hand,lift.normalize(.95*anchor+.05*src['report_gate_onehot']),'segment_lift'); pc,lg=avr.avr_inputs(ap); hpc=np.array([pc[hc==i].mean() for i in range(len(hu))]); hlg=np.vstack([lg[hc==i].mean(0) for i in range(len(hu))]); hfeat=np.hstack([hlg,hxs]); ci=np.where(hys>0)[0]; model=make_pipeline(StandardScaler(),LogisticRegression(C=C,max_iter=1500,class_weight='balanced',random_state=42)); model.fit(hfeat[ci],hys[ci]-1)
 test=audio_base.load_manifest(ROOT/'audio_visual_dataset_robo_default/dataset.csv','robot_test'); tf=suite.load_manifest(ROOT/'audio_visual_dataset_robo_default/dataset.csv',ROOT/'audio_visual_dataset_robo_default','robot_test'); yt=tf.y.to_numpy(np.int64); xt=np.load(IMG/'robot_test/X.npy').astype(np.float32); tk=seg(tf.audio_file).to_numpy(); tu,tc=np.unique(tk,return_inverse=True); tx=np.vstack([xt[tc==i].mean(0) for i in range(len(tu))]); raw=pd.read_csv(ROOT/'audio_visual_dataset_robo_default/dataset.csv'); final=pd.read_csv('outputs/audio_feature_benchmarks/audio_lift_source_blend_select/reports/audio_lift_source_blend_select_final_test_predictions.csv'); assert np.array_equal(final.audio_file.astype(str).to_numpy(),raw.audio_file.astype(str).to_numpy()); p=suite.normalize(final[suite.PROBA_COLUMNS].to_numpy(np.float64)); pc,lg=avr.avr_inputs(p); tpc=np.array([pc[tc==i].mean() for i in range(len(tu))]); tlg=np.vstack([lg[tc==i].mean(0) for i in range(len(tu))]); tm=model.predict_proba(np.hstack([tlg,tx])); predseg=np.where(tpc>=th,tm.argmax(1)+1,0); pred=predseg[tc]; by=(yt>0).astype(int); bp=(pred>0).astype(int); result={'split':'robot_test_final','protocol':lock['protocol'],'n':int(len(yt)),'locked_candidate':lock['selected_candidate'],'accuracy_4class':float(accuracy_score(yt,pred)),'macro_precision_4class':float(precision_score(yt,pred,average='macro',zero_division=0)),'macro_recall_4class':float(recall_score(yt,pred,average='macro',zero_division=0)),'macro_f1_4class':float(f1_score(yt,pred,average='macro',zero_division=0)),'weighted_f1_4class':float(f1_score(yt,pred,average='weighted',zero_division=0)),'binary_accuracy':float(accuracy_score(by,bp)),'binary_macro_precision':float(precision_score(by,bp,average='macro',zero_division=0)),'binary_macro_recall':float(recall_score(by,bp,average='macro',zero_division=0)),'binary_macro_f1':float(f1_score(by,bp,average='macro',zero_division=0)),'per_class_4class':classification_report(yt,pred,labels=[0,1,2,3],target_names=['ambient','leaf','trunk','twig'],output_dict=True,zero_division=0),'confusion_matrix_4class':confusion_matrix(yt,pred,labels=[0,1,2,3]).tolist(),'confusion_matrix_binary':confusion_matrix(by,bp,labels=[0,1]).tolist(),'invariants':{'test_loaded_after_selection_lock':True,'audio_controls_contact':True,'material_fit_contact_only':True,'group_aware_audio_oof':True,'separate_segment_aggregation':True,'raw_audio_four_class_argmax':False}}
 (OUT/'segment_joint_material_final_test_metrics.json').write_text(json.dumps(result,indent=2,default=float)); print(json.dumps(result,indent=2,default=float))
if __name__=='__main__': main()
