import json,numpy as np,pandas as pd
from pathlib import Path
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score,classification_report,confusion_matrix
import run_avr_group_selection as avr
import run_multimodal_val_locked_suite as suite
import train_audio_lift_source_blend_select_final_test as lift
import train_audio_group_consistency_pair_blend_select_final_test as ga
import train_audio_specimen_contact_consensus_select_final_test as sp
import train_val_select_final_test as audio_base
ROOT=Path('/home/ttung05/Desktop/tree_base/tree_structures'); OUT=Path('outputs/audio_feature_benchmarks/segment_bias_group_selection'); IMG=Path('outputs/image_timm_features/vit_base_patch16_clip_224.openai_ft_in1k')
def seg(s): return s.astype(str).str.replace(r'_window_\d+.*$','',regex=True)
def main():
 lock=json.load(open(OUT/'selection_lock.json')); b=lock['selected_candidate']; iw=float(b['image_weight']); tb=float(b['trunk_bias']); wb=float(b['twig_bias']); th=float(b['contact_threshold']); audio_base.configure_feature_set('total240'); h=audio_base.load_manifest(ROOT/'audio_visual_dataset_default/dataset.csv','hand_train'); hf=suite.load_manifest(ROOT/'audio_visual_dataset_default/dataset.csv',ROOT/'audio_visual_dataset_default','hand_train'); yh=hf.y.to_numpy(np.int64); hk=seg(hf.audio_file).to_numpy(); hu,hc=np.unique(hk,return_inverse=True); x=np.load(IMG/'hand_train_full/X.npy').astype(np.float32); hx=np.vstack([x[hc==i].mean(0) for i in range(len(hu))]); hy=np.array([yh[hc==i][0] for i in range(len(hu))]); model=make_pipeline(StandardScaler(),LogisticRegression(C=.03,max_iter=1200,class_weight='balanced',random_state=42)); model.fit(hx[hy>0],hy[hy>0]-1)
 test=audio_base.load_manifest(ROOT/'audio_visual_dataset_robo_default/dataset.csv','robot_test'); tf=suite.load_manifest(ROOT/'audio_visual_dataset_robo_default/dataset.csv',ROOT/'audio_visual_dataset_robo_default','robot_test'); y=tf.y.to_numpy(np.int64); tk=seg(tf.audio_file).to_numpy(); tu,tc=np.unique(tk,return_inverse=True); xt=np.load(IMG/'robot_test/X.npy').astype(np.float32); tx=np.vstack([xt[tc==i].mean(0) for i in range(len(tu))]); hi=ga.load_highsr_oof; af=pd.read_csv('outputs/audio_feature_benchmarks/audio_lift_source_blend_select/reports/audio_lift_source_blend_select_final_test_predictions.csv'); raw=pd.read_csv(ROOT/'audio_visual_dataset_robo_default/dataset.csv'); assert np.array_equal(af.audio_file.astype(str),raw.audio_file.astype(str)); p=suite.normalize(af[suite.PROBA_COLUMNS].to_numpy(np.float64)); pc,lg=avr.avr_inputs(p); spc=np.array([pc[tc==i].mean() for i in range(len(tu))]); smat=np.vstack([suite.normalize(np.exp(lg[tc==i].mean(0,keepdims=True)))[0] for i in range(len(tu))]); im=model.predict_proba(tx); mat=suite.normalize((1-iw)*smat+iw*im); mat=suite.normalize(mat*np.exp(np.array([0.,tb,wb])[None,:])); predseg=np.where(spc>=th,mat.argmax(1)+1,0); pred=predseg[tc]; by=(y>0).astype(int); bp=(pred>0).astype(int); result={'split':'robot_test_final','protocol':lock['protocol'],'locked_candidate':b,'n':len(y),'accuracy_4class':accuracy_score(y,pred),'macro_precision_4class':precision_score(y,pred,average='macro',zero_division=0),'macro_recall_4class':recall_score(y,pred,average='macro',zero_division=0),'macro_f1_4class':f1_score(y,pred,average='macro',zero_division=0),'weighted_f1_4class':f1_score(y,pred,average='weighted',zero_division=0),'binary_macro_f1':f1_score(by,bp,average='macro',zero_division=0),'per_class_4class':classification_report(y,pred,labels=[0,1,2,3],target_names=['ambient','leaf','trunk','twig'],output_dict=True,zero_division=0),'confusion_matrix_4class':confusion_matrix(y,pred,labels=[0,1,2,3]).tolist(),'no_test_leakage':True}; (OUT/'segment_bias_final_test_metrics.json').write_text(json.dumps(result,indent=2,default=float)); print(json.dumps(result,indent=2,default=float))
if __name__=='__main__': main()
