from __future__ import annotations
import json, os
from pathlib import Path
import numpy as np, pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score, recall_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
import run_multimodal_val_locked_suite as suite
import train_val_select_final_test as audio_base
ROOT=Path('/home/ttung05/Desktop/tree_base/tree_structures'); OUT=Path(os.environ.get('SEG_OUT','outputs/audio_feature_benchmarks/segment_rule_stack_resnet_fusion_group_selection'))
def features(pm,ph,pr): return np.hstack([pm,ph,pr,np.log(np.clip(pm,1e-6,1)),np.log(np.clip(ph,1e-6,1)),np.log(np.clip(pr,1e-6,1)),pm.max(1,keepdims=True),ph.max(1,keepdims=True),pr.max(1,keepdims=True)]).astype(np.float32)
def main():
    lock=json.load(open(OUT/'selection_lock.json')); assert not lock.get('test_loaded'); b=lock['selected_candidate']; c=float(b['C']); cw={0:1,1:1,2:float(b['trunk_class_weight']),3:float(b['twig_class_weight'])}; hx=np.load(OUT/'hand_oof_features.npy'); hy=np.load(OUT/'hand_oof_y.npy'); base=np.load('outputs/audio_feature_benchmarks/segment_rule_stack_v2_group_selection/segment_rule_stack_v2_base_segment_outputs.npz',allow_pickle=True); pm=base['p_meta']; ph=base['p_h']; pr=np.load(OUT/'robot_resnet_segment_proba.npy')[:,1:]; z=features(pm,ph,pr); meta=make_pipeline(StandardScaler(),LogisticRegression(C=c,max_iter=4000,class_weight=cw,multi_class='multinomial',random_state=42)); meta.fit(hx,hy); pred_seg=meta.predict(z); d=pd.read_csv(ROOT/'audio_visual_dataset_robo_default/dataset.csv'); y=d.category.map({'ambient':0,'leaf':1,'trunk':2,'twig':3}).to_numpy(np.int64); rowseg=d.audio_file.str.replace(r'_window_\d+.*$','',regex=True).to_numpy(); ids=base['segment_ids'].astype(str); order={k:i for i,k in enumerate(ids)}; pred=np.array([pred_seg[order[k]] for k in rowseg]); by=(y>0).astype(int); bp=(pred>0).astype(int); result={'split':'robot_test_final','protocol':lock['protocol'],'n':int(len(y)),'locked_candidate':b,'metrics':{'accuracy_4class':float(accuracy_score(y,pred)),'macro_precision_4class':float(precision_score(y,pred,average='macro',zero_division=0)),'macro_recall_4class':float(recall_score(y,pred,average='macro',zero_division=0)),'macro_f1_4class':float(f1_score(y,pred,average='macro',zero_division=0)),'weighted_f1_4class':float(f1_score(y,pred,average='weighted',zero_division=0)),'binary_accuracy':float(accuracy_score(by,bp)),'binary_macro_precision':float(precision_score(by,bp,average='macro',zero_division=0)),'binary_macro_recall':float(recall_score(by,bp,average='macro',zero_division=0)),'binary_macro_f1':float(f1_score(by,bp,average='macro',zero_division=0))},'per_class_4class':classification_report(y,pred,labels=[0,1,2,3],target_names=['ambient','leaf','trunk','twig'],output_dict=True,zero_division=0),'confusion_matrix_4class':confusion_matrix(y,pred,labels=[0,1,2,3]).tolist(),'confusion_matrix_binary':confusion_matrix(by,bp,labels=[0,1]).tolist(),'invariants':{'selection_used_hand_only':True,'test_loaded_after_lock':True,'no_new_split':True}}
    (OUT/'segment_rule_stack_resnet_fusion_final_test_metrics.json').write_text(json.dumps(result,indent=2,default=float)); print(json.dumps(result,indent=2,default=float))
if __name__=='__main__': main()
